language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

# Setup anaconda
before_install:
  - sudo apt-get -qq update

# Install packages
install:
  - pip install --upgrade pip
  - pip install --upgrade wheel setuptools
  - pip install --upgrade numpy
  - pip install --upgrade matplotlib
  - pip install --upgrade pandas
  - pip install --upgrade scipy
  - pip install --upgrade coveralls
  - python setup.py install

script:
  - source activate $TRAVIS_PYTHON_VERSION
  - nosetests --with-doctest --with-coverage --cover-tests --cover-package=swmmtoolbox --cover-branches --cover-erase

after_success:
  - coveralls
