language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7-dev

# Setup anaconda
before_install:
  - sudo apt-get -qq update

# Install packages
install:
  - pip install --upgrade pip
  - pip install wheel
  - pip install numpy
  - pip install matplotlib
  - pip install pandas
  - pip install scipy
  - pip install xlsxwriter
  - pip install coveralls
  - python setup.py install

script:
  - source activate $TRAVIS_PYTHON_VERSION
  - nosetests --with-doctest --with-coverage --cover-tests --cover-package=swmmtoolbox --cover-branches --cover-erase

after_success:
  - coveralls

