language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

cache:
  pip: true
  directories:
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
    - $HOME/.cache/matplotlib

# Setup anaconda
before_install:
  - sudo apt-get -qq update

# Install packages
install:
  - pip install --upgrade pip
  - pip install --upgrade wheel setuptools
  - pip install --upgrade numpy
  - pip install --upgrade matplotlib
  - pip install --upgrade pandas
  - pip install --upgrade scipy
  - pip install --upgrade coveralls
  - python setup.py install

script:
  - source activate $TRAVIS_PYTHON_VERSION
  - pytest --cov swmmtoolbox --doctest-modules --ignore=docsrc --mpl

after_success:
  - coveralls
